export const categories = [
  { emoji: "📱", label: "Electrónica", query: "electronics" },
  { emoji: "👟", label: "Ropa y Calzado", query: "clothing+shoes" },
  { emoji: "🏋️‍♂️", label: "Deportes y Fitness", query: "sports+fitness" },
  { emoji: "🍳", label: "Cocina", query: "kitchen" },
  { emoji: "💄", label: "Belleza", query: "beauty" },
  { emoji: "🛋️", label: "Hogar", query: "home+decor" },
  { emoji: "🎮", label: "Videojuegos", query: "video+games" },
  { emoji: "📚", label: "Libros", query: "books" },
  { emoji: "🧸", label: "Juguetes", query: "toys" },
  { emoji: "💻", label: "Computación", query: "computers" },
  { emoji: "🎧", label: "Audio", query: "headphones" },
  { emoji: "🚗", label: "Automotriz", query: "automotive" },
  { emoji: "👶", label: "Bebés", query: "baby" },
  { emoji: "🐶", label: "Mascotas", query: "pet+supplies" },
  { emoji: "🖼️", label: "Arte y Manualidades", query: "arts+crafts" },
  { emoji: "🧼", label: "Cuidado Personal", query: "personal+care" },
  { emoji: "⛺", label: "Camping y Outdoor", query: "outdoor+recreation" },
  { emoji: "💡", label: "Iluminación", query: "lighting" },
  { emoji: "🧳", label: "Viajes", query: "travel+gear" },
  { emoji: "🪑", label: "Muebles", query: "furniture" },
  { emoji: "🛠️", label: "Herramientas", query: "tools+hardware" },
  { emoji: "🏫", label: "Escolar y Oficina", query: "office+school+supplies" },
  { emoji: "🕶️", label: "Accesorios", query: "fashion+accessories" },
  { emoji: "🧃", label: "Comida y Bebida", query: "grocery" },
];
